version: '3.8'

services:
  backend:
    build: .
    container_name: chat-backend
    ports:
      - '5000:5000'  # ✅ Expose your Express/Socket.IO backend
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'  # ✅ Map 5433 on host to 5432 in container

volumes:
  pgdata:

